name: MyFamilyTree
options:
  bundleIdPrefix: com.aries-rst.myfamilytree
  deploymentTarget:
    iOS: "16.0"
  createIntermediateGroups: true
configs:
  Debug: debug
  Release: release
targets:
  MyFamilyTree:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - MyFamilyTree
    info:
      path: MyFamilyTree/Info.plist
      properties:
        CFBundleDisplayName: "MyFamilyTree"
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.aries-rst.myfamilytree.app
        MARKETING_VERSION: "1.0"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CURRENT_PROJECT_VERSION: "4"
        SWIFT_VERSION: "5.0"
        TARGETED_DEVICE_FAMILY: "1,2"
        ENABLE_PREVIEWS: YES
schemes:
  MyFamilyTree:
    build:
      targets:
        MyFamilyTree: all
    run:
      config: Debug
    test:
      config: Debug
    archive:
      config: Release
